### ISSUE TITLE
Warning message from flow-runtime

### ISSUE THREAD

**Issue by vonagam** [jcoreio/promake#19]
Keep getting this one:

`flow-runtime: Could not reference the given type, try t.typeOf(value) instead.`

Originates from [here](https://github.com/jcoreio/promake/blob/de7c1d083ec0e18222f7b6725f2fa014c0f8564e/src/TaskResource.js#L8). It seems like `Promake` imports `TaskResource`, and `TaskResource` tries to get type reference for `Promake`, but is is not defined yet as it needs `TaskResource`.

**Comment by jedwards1211** [comment]
I haven't figured this out yet, since I'm using `babel-plugin-flow-runtime` to generate the flow-runtime types instead of writing them manually, I'm not sure if there's an easy fix for this.  Maybe I should just scrap usage of `flow-runtime` in this package for now...

**Comment by yanick** [comment]
:poke: It it helps, I can create a PR for it?

**Comment by jedwards1211** [comment]
Ouch, sorry I let this languish...let me go ahead and take care of it

**Comment by jedwards1211** [comment]
@yanick okay in a moment the release notification should appear...with my changes, I didn't see the warning in the console during tests, but don't hesitate to let me know if it rears its head again

**Comment by yanick** [comment]
Woot! Thanks a lot!
